<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pos;

class PosSeeder extends Seeder
{
    public function run(): void
    {
        Pos::truncate();

        $data = [
            [
                'nama'              => 'Baleendah',
                'kode_pos'          => 'POS-BLE',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 0,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 1,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 0,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Baleendah',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Cicalengka',
                'kode_pos'          => 'POS-CCK',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 6,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 1,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Cicalengka',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Cileunyi',
                'kode_pos'          => 'POS-CLY',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 0,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 0,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Cileunyi',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Ciparay',
                'kode_pos'          => 'POS-CPR',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 6,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 1,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Ciparay',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Ciwidey (Pacira)',
                'kode_pos'          => 'POS-CWD',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 0,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 0,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Ciwidey',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Majalaya',
                'kode_pos'          => 'POS-MJL',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 0,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 0,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Majalaya',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Margaasih (TKI)',
                'kode_pos'          => 'POS-MGA',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 0,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 0,
                'unit_water_supply' => 0,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Margaasih',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Pangalengan',
                'kode_pos'          => 'POS-PGL',
                'personil_pemadam'  => 8,
                'personil_rescue'   => 0,
                'personil_cc'       => 0,
                'unit_truck_pancar' => 1,
                'unit_motor_roda3'  => 0,
                'unit_motor_roda2'  => 0,
                'unit_pompa'        => 0,
                'unit_rescue'       => 0,
                'unit_water_supply' => 1,
                'unit_lainnya'      => 0,
                'wilayah'           => 'Pangalengan',
                'status'            => 'aktif',
            ],
            [
                'nama'              => 'Soreang (MAKO)',
                'kode_pos'          => 'POS-SRG',
                'personil_pemadam'  => 16,
                'personil_rescue'   => 8,
                'personil_cc'       => 4,
                'unit_truck_pancar' => 3,
                'unit_motor_roda3'  => 1,
                'unit_motor_roda2'  => 2,
                'unit_pompa'        => 3,
                'unit_rescue'       => 1,
                'unit_water_supply' => 1,
                'unit_lainnya'      => 2,
                'wilayah'           => 'Soreang',
                'status'            => 'aktif',
            ],
        ];

        foreach ($data as $pos) {
            Pos::create($pos);
        }
    }
}
