<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Unit;

class UnitSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Kosongkan tabel units
        Unit::truncate();

        // 2. Daftar 25 Armada Unit Kendaraan Resmi dari Dinas Damkar & Penyelamatan
        $units = [
            [
                'nomor_lambung'   => 'P-01',
                'plat_nomor'      => 'D 8518 V',
                'no_rangka_mesin' => 'FG8JJ1D-BGJ',
                'merk_tipe'       => 'HINO (4X4)',
                'tahun_pembuatan' => 2018,
                'cc'              => '7684',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'UDEN SUHENDI',
                'pengemudi_2'     => 'MUHAMAD ILHAM',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-02',
                'plat_nomor'      => 'D 9923 Z',
                'no_rangka_mesin' => 'WU342R-HKMRJD3L',
                'merk_tipe'       => 'HINO (130MDL)',
                'tahun_pembuatan' => 2017,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'UDEN SUHENDI',
                'pengemudi_2'     => 'MUHAMAD ILHAM',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-03',
                'plat_nomor'      => 'NKR81',
                'no_rangka_mesin' => 'NKR81-7000441',
                'merk_tipe'       => 'ISUZU',
                'tahun_pembuatan' => 2004,
                'cc'              => '3000',
                'jenis_peruntukan' => 'POMPA/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'TAOPIK S',
                'pengemudi_2'     => 'MARYO KUSWANTO',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-04',
                'plat_nomor'      => 'D 9429 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'ISUZU BORNEO/ FTR33',
                'tahun_pembuatan' => 2003,
                'cc'              => '8226',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'TKI',
                'pengemudi_1'     => 'RIKI ROHIMAT',
                'pengemudi_2'     => 'DEPEN RUSTANDI',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-05',
                'plat_nomor'      => 'D 9921 V',
                'no_rangka_mesin' => 'WU342R-HKMTJD3',
                'merk_tipe'       => 'HINO (130HD)',
                'tahun_pembuatan' => 2013,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'PANGALENGAN',
                'pengemudi_1'     => 'ROSI ROSMAWAN',
                'pengemudi_2'     => 'YOGA NURHAMDANI',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-06',
                'plat_nomor'      => 'D 9932 V',
                'no_rangka_mesin' => 'WU342R-HKMRJD3L',
                'merk_tipe'       => 'HINO (130MDL)',
                'tahun_pembuatan' => 2014,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'CIPARAY',
                'pengemudi_1'     => 'IKHBAL NOOR WIBAWA',
                'pengemudi_2'     => 'AJI SETIAJI',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-07',
                'plat_nomor'      => 'D 9914 V',
                'no_rangka_mesin' => 'WU342R-HKMTJD3',
                'merk_tipe'       => 'HINO (130HD)',
                'tahun_pembuatan' => 2012,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'MAJALAYA',
                'pengemudi_1'     => 'DIDIK TRIYONO',
                'pengemudi_2'     => 'HENDRI INDRA UTAMA',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-08',
                'plat_nomor'      => 'D 9060 V',
                'no_rangka_mesin' => 'WU342R-HKMRJD3L',
                'merk_tipe'       => 'HINO (130MDL)',
                'tahun_pembuatan' => 2015,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'CICALENGKA',
                'pengemudi_1'     => 'DODI ROMANSYAH',
                'pengemudi_2'     => 'DANI HADIANA',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-09',
                'plat_nomor'      => 'D 9920 Z',
                'no_rangka_mesin' => 'WU342R-HKMRJD3L',
                'merk_tipe'       => 'HINO (130MDL)',
                'tahun_pembuatan' => 2017,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'CILEUNYI',
                'pengemudi_1'     => 'EGIT SUPRIADI SAPUTRA',
                'pengemudi_2'     => 'INDRA ADHADY N',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-10',
                'plat_nomor'      => 'D 8559 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'HINO DUTRO 136 HDL',
                'tahun_pembuatan' => 2024,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'TAOPIK S',
                'pengemudi_2'     => 'MARYO KUSWANTO',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-11',
                'plat_nomor'      => 'D 9958 Y',
                'no_rangka_mesin' => 'XZU349R-HKMTBD3',
                'merk_tipe'       => 'HINO XZU349R-HKMTBD3',
                'tahun_pembuatan' => 2024,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'BALEENDAH',
                'pengemudi_1'     => 'WIBBY KHAYATUL FAUZI',
                'pengemudi_2'     => 'RIKI TEGUH H',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'P-12',
                'plat_nomor'      => 'D 9957 Y',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'HINO 300 SERIES',
                'tahun_pembuatan' => 2024,
                'cc'              => '4009',
                'jenis_peruntukan' => 'PANCAR/PEMADAMAN',
                'pos'             => 'PACIRA',
                'pengemudi_1'     => 'DIKI TABRONI',
                'pengemudi_2'     => 'SANDY SUNDARA',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'S-01',
                'plat_nomor'      => 'D 8517 V',
                'no_rangka_mesin' => 'WJ342R-HKMTJD3',
                'merk_tipe'       => 'HINO (130HD)',
                'tahun_pembuatan' => 2018,
                'cc'              => '4009',
                'jenis_peruntukan' => 'SUPPLY/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'RAHMAT GUMILAR',
                'pengemudi_2'     => 'MARYO KUSWANTO',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'S-02',
                'plat_nomor'      => 'D 8516 V',
                'no_rangka_mesin' => 'WJ342R-HKMTJD3',
                'merk_tipe'       => 'HINO (130HD)',
                'tahun_pembuatan' => 2018,
                'cc'              => '4009',
                'jenis_peruntukan' => 'SUPPLY/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'UDEN SUHENDI',
                'pengemudi_2'     => 'MUHAMAD ILHAM',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'R-01',
                'plat_nomor'      => 'D 9933 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'HINO',
                'tahun_pembuatan' => 2018,
                'cc'              => '4009',
                'jenis_peruntukan' => 'RESCUE/RESCUE',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'AMUNG S',
                'pengemudi_2'     => 'NUNU NUGRAHA',
                'kategori'        => 'rescue',
            ],
            [
                'nomor_lambung'   => 'R-02',
                'plat_nomor'      => 'NKR816',
                'no_rangka_mesin' => 'NKR816-7000009',
                'merk_tipe'       => 'ISUZU',
                'tahun_pembuatan' => 2002,
                'cc'              => '3000',
                'jenis_peruntukan' => 'POMPA/RESCUE',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'TAOPIK S',
                'pengemudi_2'     => 'MARYO KUSWANTO',
                'kategori'        => 'rescue',
            ],
            [
                'nomor_lambung'   => 'R-03',
                'plat_nomor'      => 'NKR71G',
                'no_rangka_mesin' => 'NKR71G-7403639',
                'merk_tipe'       => 'ISUZU',
                'tahun_pembuatan' => 1999,
                'cc'              => '3000',
                'jenis_peruntukan' => 'POMPA/RESCUE',
                'pos'             => 'CIPARAY',
                'pengemudi_1'     => 'WAWAN GUNAWAN',
                'pengemudi_2'     => 'RAMDANI NURAPRIANTO',
                'kategori'        => 'rescue',
            ],
            [
                'nomor_lambung'   => 'R-04',
                'plat_nomor'      => 'D 9964 Y',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'HILUX DOUBLE CABIN',
                'tahun_pembuatan' => 2024,
                'cc'              => '2393',
                'jenis_peruntukan' => 'RESCUE/RESCUE',
                'pos'             => 'CICALENGKA',
                'pengemudi_1'     => 'RINDAM NUR APRIADI',
                'pengemudi_2'     => 'WILY SUMANTRI',
                'kategori'        => 'rescue',
            ],
            [
                'nomor_lambung'   => 'K-01',
                'plat_nomor'      => 'D 8507 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'HILUX DOUBLE CABIN',
                'tahun_pembuatan' => 2018,
                'cc'              => '2393',
                'jenis_peruntukan' => 'PICK UP/KOMANDO',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'EKO PRASETYO',
                'pengemudi_2'     => '—',
                'kategori'        => 'rescue',
            ],
            [
                'nomor_lambung'   => 'PC-01',
                'plat_nomor'      => 'D 8508 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'HILUX DOUBLE CABIN',
                'tahun_pembuatan' => 2018,
                'cc'              => '2393',
                'jenis_peruntukan' => 'PICK UP/PENCEGAHAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'WIGARA',
                'pengemudi_2'     => 'ZALFA ZAHIYA',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'PC-02',
                'plat_nomor'      => 'RZY230',
                'no_rangka_mesin' => 'RZY230-0001838',
                'merk_tipe'       => 'ISUZU',
                'tahun_pembuatan' => 2000,
                'cc'              => '2499',
                'jenis_peruntukan' => 'POMPA/PENCEGAHAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'WIGARA',
                'pengemudi_2'     => 'ZALFA ZAHIYA',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'MP-01',
                'plat_nomor'      => 'D 3296 Z',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'KAWASAKI VERYSEX',
                'tahun_pembuatan' => 2024,
                'cc'              => '250',
                'jenis_peruntukan' => 'R2/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'M. ARIF R',
                'pengemudi_2'     => '—',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'MP-02',
                'plat_nomor'      => 'D 3297 Z',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'KAWASAKI VERYSEX',
                'tahun_pembuatan' => 2024,
                'cc'              => '250',
                'jenis_peruntukan' => 'R2/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => 'TAUDIN FUAD',
                'pengemudi_2'     => '—',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'MP-03',
                'plat_nomor'      => 'D 5650 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'VIAR',
                'tahun_pembuatan' => 2018,
                'cc'              => '200',
                'jenis_peruntukan' => 'R3/PEMADAMAN',
                'pos'             => 'SOREANG',
                'pengemudi_1'     => '—',
                'pengemudi_2'     => '—',
                'kategori'        => 'pemadam',
            ],
            [
                'nomor_lambung'   => 'MP-04',
                'plat_nomor'      => 'D 5651 V',
                'no_rangka_mesin' => '—',
                'merk_tipe'       => 'VIAR',
                'tahun_pembuatan' => 2018,
                'cc'              => '200',
                'jenis_peruntukan' => 'R3/PEMADAMAN',
                'pos'             => 'BALEENDAH',
                'pengemudi_1'     => 'REDKAR',
                'pengemudi_2'     => '—',
                'kategori'        => 'pemadam',
            ],
        ];

        foreach ($units as $u) {
            $parts = explode('/', $u['jenis_peruntukan'] ?? '');
            $jenis = trim($parts[0] ?? '');
            $peruntukan = trim($parts[1] ?? '');

            Unit::create([
                'nama'            => "{$u['nomor_lambung']} - {$u['merk_tipe']}",
                'kategori'        => $u['kategori'],
                'nomor_lambung'   => $u['nomor_lambung'],
                'plat_nomor'      => $u['plat_nomor'],
                'no_rangka_mesin' => $u['no_rangka_mesin'],
                'merk_tipe'       => $u['merk_tipe'],
                'tahun_pembuatan' => $u['tahun_pembuatan'],
                'cc'              => $u['cc'],
                'jenis_kendaraan' => $jenis ?: null,
                'peruntukan'      => $peruntukan ?: null,
                'pos'             => $u['pos'],
                'pengemudi_1'     => $u['pengemudi_1'],
                'pengemudi_2'     => $u['pengemudi_2'],
                'status'          => 'aktif',
                'catatan'         => 'Armada operasional unit dinas.',
            ]);
        }
    }
}
